version: '3'

services:
  nginx:
    build:
      context: ./nginx  # 현재 디렉토리를 빌드 컨텍스트로 사용
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - fairy_book_front

  fairy_book_front:
    build:
      context: ./fairy_book_front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - fairy_book_data
    environment:
      - DANGEROUSLY_DISABLE_HOST_CHECK=true

  fairy_book_data:
    build:
      context: ./fiary_book_data
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - TESTING=False
      - SECRET_KEY=your_secret_key
      - OPENAI_KEY=your_openai_key